- link:
    ~/.local/bin/:
      path: bash/**
      glob: true

- shell:
    - wget https://github.com/dbrgn/tealdeer/releases/download/v1.5.0/tealdeer-linux-x86_64-musl -O ~/.local/bin/tealdeer
    - tealdeer --update
    - wget https://github.com/chmln/sd/releases/download/v0.7.6/sd-v0.7.6-x86_64-unknown-linux-gnu -O ~/.local/bin/sd
    - wget https://github.com/so-fancy/diff-so-fancy/releases/download/v1.4.3/diff-so-fancy -O ~/.local/bin/diff-so-fancy
    - wget https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64 -O  ~/.local/bin/ctop
    - wget https://dystroy.org/broot/download/x86_64-linux/broot -O ~/.local/bin/broot
    - wget https://dystroy.rg/broot/download/x86_64-linux/broot -O ~/.local/bin/broot
    - curl -s https://github.com/jesseduffield/lazygit/releases/download/v0.34/lazygit_0.34_Linux_x86_64.tar.gz | tar xf -C ~/.local/bin/lazygit
    - curl -L -o - https://github.com/dalance/procs/releases/download/v0.12.3/procs-v0.12.3-x86_64-linux.zip | gunzip > ~/.local/bin/procs
    - chmod 775 -R ~/.local/bin/

- apt:
    - gping
