- shell:
    - curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
    - curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
    - wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -
    - echo "deb http://packages.azlux.fr/debian/ stable main" | sudo tee /etc/apt/sources.list.d/azlux.list
    - wget https://github.com/sharkdp/hyperfine/releases/download/v1.13.0/hyperfine_1.13.0_amd64.deb
    - wget https://github.com/bootandy/dust/releases/download/v0.8.1/du-dust_0.8.1_amd64.deb
    - dpkg -i hyperfine_1.13.0_amd64.deb du-dust_0.8.1_amd64.deb && rm *.deb

- apt:
    - bat
    - fd-find
    - ripgrep
    - exa
    - httpie
