image: nixos/nix

stages:
  - deploy

tailscale:
  stage: deploy
  script:
    - nix-shell -p tailscale --run tailscaled --state="mem:" &
    - tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname="gitlab-$(cat /etc/hostname)" --accept-routes
    - tailscale status
